watermeter:
  d1:
    model: dig-cont_0900_s3_q
    predecimal:
    - [209, 131, 33, 46]
    - [255, 126, 36, 51]
    - [303, 128, 41, 54]
    - [356, 130, 36, 51]
    - [404, 128, 36, 49]
  a1:
    model: ana-cont_1500_s2_q
    rects:
    - [165, 333, 97, 95]
  a2:
    model: ana-cont_1500_s2_q
    rects:
    - [291, 370, 105, 96]
  a3:
    model: ana-cont_1500_s2_q
    rects:
    - [392, 329, 100, 97]
  a4:
    model: ana-cont_1500_s2_q
    rects:
    - [443, 232, 96, 93]
  t1:
    model: tesseract
    rects:
    - [305, 188, 162, 30]


pv:
  pv:
    model: tesseract
    rects:
    - [194, 92, 52, 23]
  net:
    model: tesseract
    rects:
    - [335, 206, 60, 23]
  home:
    model: tesseract
    rects:
    - [190, 316, 52, 20]
  bat:
    model: tesseract
    rects:
    - [44, 206, 52, 21]
  bat-p:
    model: tesseract
    rects:
    - [51, 172, 42, 25]
