mqtt:
  host: 192.168.0.165
  port: 1883
  topic_base: meters
watermeter:
  d1:
    model: dig-cont_0900_s3_q
    predecimal:
    - [209, 131, 33, 46]
    - [255, 126, 36, 51]
    - [303, 128, 41, 54]
    - [356, 130, 36, 51]
    - [404, 128, 36, 49]
  a1:
    model: ana-cont_1500_s2_q
    rects:
    - [165, 333, 97, 95]
  a2:
    model: ana-cont_1500_s2_q
    rects:
    - [291, 370, 105, 96]
  a3:
    model: ana-cont_1500_s2_q
    rects:
    - [392, 329, 100, 97]
  a4:
    model: ana-cont_1500_s2_q
    rects:
    - [443, 232, 96, 93]
  t1:
    model: tesseract
    rects:
    - [305, 188, 162, 30]
pv:
  pv:
    model: tesseract
    rects:
    - [195, 90, 54, 28]
    match: \d+(\.\d+)?
  bat:
    model: tesseract
    rects:
    - [46, 200, 56, 26]
    match: \d+(\.\d+)?
  bat-p:
    model: tesseract
    rects:
    - [51, 174, 42, 18]
    match: '[0-9]+\%'
  home:
    model: tesseract
    rects:
    - [190, 311, 62, 30]
    match: \d+(\.\d+)?
  net:
    model: tesseract
    rects:
    - [339, 203, 57, 27]
    match: \d+(\.\d+)?
  transform: balance_sum_zero
uhr-1:
  rotate: -90
  padding: 0.1
  enhance:
  - autocontrast
  temp:
    model: digital-class100
    predecimal:
      - [259, 334, 27, 46]
      - [287, 334, 27, 46]
    postdecimal:
      - [313, 334, 27, 46]
    range: [ 0.0, 29.0 ]          
  zeit:
    model: digital-class100
    predecimal:
      - [214, 217, 36, 57]
      - [246, 217, 35, 56]
    postdecimal:
      - [286, 216, 34, 57]
      - [324, 218, 40, 57]
    range: [ 0.0, 24.0 ]
    match: '[0-2][0-9]\.[0-5][0-9]' 
    

uhr-2:
  rotate: 0
  padding: 0.2
  enhance:
  - autocontrast
  temp:
    model: digital-class100
    predecimal:
      - [252, 306, 26, 43]
      - [281, 305, 24, 46]
    postdecimal:
      - [309, 304, 26, 47]
    range: [ 0.0, 29.0 ]          
  zeit:
    model: digital-class100
    predecimal:
      - [208, 185, 29, 61]
      - [237, 186, 34, 62]
    postdecimal:
      - [278, 182, 34, 63]
      - [316, 181, 36, 65]
    range: [ 0.0, 24.0 ]
    match: '[0-2][0-9]\.[0-5][0-9]' 
      

  
    
    


    
    

